# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: handles_sortable_columns 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "handles_sortable_columns"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alex Fortuna"]
  s.date = "2017-06-29"
  s.description = "Sortable Table Columns"
  s.email = "alex.r@askit.org"
  s.extra_rdoc_files = [
    "README.html",
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.html",
    "README.md",
    "Rakefile",
    "VERSION.yml",
    "handles_sortable_columns.gemspec",
    "init.rb",
    "lib/action_controller/base/handles_sortable_columns.rb",
    "lib/handles/sortable_columns.rb",
    "lib/handles_sortable_columns.rb"
  ]
  s.homepage = "http://github.com/dadooda/handles_sortable_columns"
  s.rubygems_version = "2.4.8"
  s.summary = "Sortable Table Columns"
end

